# Generated by Django 4.2.1 on 2023-06-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('internal_reference', models.CharField(max_length=255)),
                ('responsible', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('quantity_on_hand', models.IntegerField()),
                ('forecasted_quantity', models.IntegerField()),
                ('activity_exception_decoration', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_company', models.BooleanField()),
                ('related_company', models.CharField(max_length=255)),
                ('address_type', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=255)),
                ('purchase_representative', models.CharField(max_length=255)),
                ('order_deadline', models.DateField()),
                ('activities', models.CharField(max_length=255)),
                ('source_document', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=255)),
                ('order_reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mspurchasingapp.product', to_field='name')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mspurchasingapp.vendor')),
            ],
        ),
    ]
