# Generated by Django 4.2.1 on 2023-06-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mspurchasingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='source_document',
            field=models.FileField(upload_to='purchase_orders/source_document/'),
        ),
    ]
