# Generated by Django 4.2.1 on 2023-06-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mspurchasingapp', '0003_alter_purchaseorder_source_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='source_document',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/source_document/'),
        ),
    ]
